# Generated by Django 5.2 on 2025-04-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_floor_floor'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cakes',
            field=models.ManyToManyField(blank=True, related_name='user', to='mainapp.cake', verbose_name='Заказы тортов'),
        ),
    ]
