# Generated by Django 5.2 on 2025-04-14 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Обложка')),
                ('likes', models.IntegerField(default=0, verbose_name='Лайки')),
                ('description', models.TextField(verbose_name='Описание')),
                ('slug', models.SlugField(blank=True, max_length=200, verbose_name='URL')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='users.user', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
    ]
