# Generated by Django 5.2 on 2025-04-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryingredient',
            name='slug',
            field=models.CharField(blank=True, max_length=220, null=True, verbose_name='Slug'),
        ),
    ]
