# Generated by Django 5.2 on 2025-04-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_categoryingredient_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients', models.ManyToManyField(blank=True, related_name='floors', to='mainapp.ingredient', verbose_name='Ингредиенты')),
            ],
            options={
                'verbose_name': 'Ярус торта',
                'verbose_name_plural': 'Ярусы торта',
            },
        ),
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИО')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('amount', models.FloatField(default=1, verbose_name='Цена заказа')),
                ('date_delivery', models.CharField(blank=True, max_length=20, null=True, verbose_name='Дата доставки')),
                ('time_delivery', models.CharField(blank=True, max_length=20, null=True, verbose_name='Время доставки')),
                ('type_cake', models.CharField(blank=True, choices=[('one', 'Одноярусный'), ('more', 'Ярусный')], max_length=30, verbose_name='Тип торта')),
                ('form', models.CharField(blank=True, choices=[('circle', 'Круг'), ('hexagon', 'Шестигранник'), ('square', 'Квадрат')], max_length=40, null=True, verbose_name='Форма торта')),
                ('date_order', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('floors', models.ManyToManyField(blank=True, related_name='cake', to='mainapp.floor', verbose_name='Ярусы')),
            ],
            options={
                'verbose_name': 'Заказ торта',
                'verbose_name_plural': 'Заказ тортов',
            },
        ),
    ]
