# Generated by Django 5.2 on 2025-04-27 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_floor_cake'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='floor',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер яруса'),
        ),
    ]
