# Generated by Django 5.2 on 2025-04-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_floor_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес'),
        ),
    ]
