# Generated by Django 5.2 on 2025-04-22 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_products',
            field=models.ManyToManyField(blank=True, related_name='cart', to='products.cartproduct', verbose_name='Продукты в корзине'),
        ),
    ]
