# Generated by Django 5.2 on 2025-04-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_cart_cart_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='pickup',
        ),
        migrations.AddField(
            model_name='delivery',
            name='pvz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Пункт выдачи'),
        ),
    ]
