# Generated by Django 5.2 on 2025-04-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_delivery_pickup_delivery_pvz'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='date_delivery',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Дата доставки'),
        ),
    ]
