# Generated by Django 5.2 on 2025-04-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_delivery_date_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type_pay',
            field=models.CharField(blank=True, choices=[('online', 'Оплата онлайн'), ('cash', 'Оплата при получении')], max_length=70, null=True, verbose_name='Способ оплаты'),
        ),
    ]
